// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatSupport.proto

package grpc.ca.ChatSupport;

/**
 * Protobuf type {@code HelloRequest4}
 */
public  final class HelloRequest4 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HelloRequest4)
    HelloRequest4OrBuilder {
private static final long serialVersionUID = 0L;
  // Use HelloRequest4.newBuilder() to construct.
  private HelloRequest4(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloRequest4() {
    name4_ = "";
    name5_ = "";
    name6_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HelloRequest4(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name4_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name5_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name6_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ca.ChatSupport.NewServiceImpl3.internal_static_HelloRequest4_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ca.ChatSupport.NewServiceImpl3.internal_static_HelloRequest4_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ca.ChatSupport.HelloRequest4.class, grpc.ca.ChatSupport.HelloRequest4.Builder.class);
  }

  public static final int NAME4_FIELD_NUMBER = 1;
  private volatile java.lang.Object name4_;
  /**
   * <code>string name4 = 1;</code>
   */
  public java.lang.String getName4() {
    java.lang.Object ref = name4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name4_ = s;
      return s;
    }
  }
  /**
   * <code>string name4 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getName4Bytes() {
    java.lang.Object ref = name4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME5_FIELD_NUMBER = 2;
  private volatile java.lang.Object name5_;
  /**
   * <code>string name5 = 2;</code>
   */
  public java.lang.String getName5() {
    java.lang.Object ref = name5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name5_ = s;
      return s;
    }
  }
  /**
   * <code>string name5 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getName5Bytes() {
    java.lang.Object ref = name5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME6_FIELD_NUMBER = 3;
  private volatile java.lang.Object name6_;
  /**
   * <code>string name6 = 3;</code>
   */
  public java.lang.String getName6() {
    java.lang.Object ref = name6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name6_ = s;
      return s;
    }
  }
  /**
   * <code>string name6 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getName6Bytes() {
    java.lang.Object ref = name6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getName4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name4_);
    }
    if (!getName5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name5_);
    }
    if (!getName6Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name6_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getName4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name4_);
    }
    if (!getName5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name5_);
    }
    if (!getName6Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name6_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ca.ChatSupport.HelloRequest4)) {
      return super.equals(obj);
    }
    grpc.ca.ChatSupport.HelloRequest4 other = (grpc.ca.ChatSupport.HelloRequest4) obj;

    boolean result = true;
    result = result && getName4()
        .equals(other.getName4());
    result = result && getName5()
        .equals(other.getName5());
    result = result && getName6()
        .equals(other.getName6());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME4_FIELD_NUMBER;
    hash = (53 * hash) + getName4().hashCode();
    hash = (37 * hash) + NAME5_FIELD_NUMBER;
    hash = (53 * hash) + getName5().hashCode();
    hash = (37 * hash) + NAME6_FIELD_NUMBER;
    hash = (53 * hash) + getName6().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.ChatSupport.HelloRequest4 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ca.ChatSupport.HelloRequest4 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HelloRequest4}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HelloRequest4)
      grpc.ca.ChatSupport.HelloRequest4OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ca.ChatSupport.NewServiceImpl3.internal_static_HelloRequest4_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ca.ChatSupport.NewServiceImpl3.internal_static_HelloRequest4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ca.ChatSupport.HelloRequest4.class, grpc.ca.ChatSupport.HelloRequest4.Builder.class);
    }

    // Construct using grpc.ca.ChatSupport.HelloRequest4.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name4_ = "";

      name5_ = "";

      name6_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ca.ChatSupport.NewServiceImpl3.internal_static_HelloRequest4_descriptor;
    }

    @java.lang.Override
    public grpc.ca.ChatSupport.HelloRequest4 getDefaultInstanceForType() {
      return grpc.ca.ChatSupport.HelloRequest4.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ca.ChatSupport.HelloRequest4 build() {
      grpc.ca.ChatSupport.HelloRequest4 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ca.ChatSupport.HelloRequest4 buildPartial() {
      grpc.ca.ChatSupport.HelloRequest4 result = new grpc.ca.ChatSupport.HelloRequest4(this);
      result.name4_ = name4_;
      result.name5_ = name5_;
      result.name6_ = name6_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ca.ChatSupport.HelloRequest4) {
        return mergeFrom((grpc.ca.ChatSupport.HelloRequest4)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ca.ChatSupport.HelloRequest4 other) {
      if (other == grpc.ca.ChatSupport.HelloRequest4.getDefaultInstance()) return this;
      if (!other.getName4().isEmpty()) {
        name4_ = other.name4_;
        onChanged();
      }
      if (!other.getName5().isEmpty()) {
        name5_ = other.name5_;
        onChanged();
      }
      if (!other.getName6().isEmpty()) {
        name6_ = other.name6_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ca.ChatSupport.HelloRequest4 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ca.ChatSupport.HelloRequest4) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name4_ = "";
    /**
     * <code>string name4 = 1;</code>
     */
    public java.lang.String getName4() {
      java.lang.Object ref = name4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name4 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getName4Bytes() {
      java.lang.Object ref = name4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name4 = 1;</code>
     */
    public Builder setName4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name4 = 1;</code>
     */
    public Builder clearName4() {
      
      name4_ = getDefaultInstance().getName4();
      onChanged();
      return this;
    }
    /**
     * <code>string name4 = 1;</code>
     */
    public Builder setName4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name4_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name5_ = "";
    /**
     * <code>string name5 = 2;</code>
     */
    public java.lang.String getName5() {
      java.lang.Object ref = name5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name5 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getName5Bytes() {
      java.lang.Object ref = name5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name5 = 2;</code>
     */
    public Builder setName5(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name5 = 2;</code>
     */
    public Builder clearName5() {
      
      name5_ = getDefaultInstance().getName5();
      onChanged();
      return this;
    }
    /**
     * <code>string name5 = 2;</code>
     */
    public Builder setName5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name5_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name6_ = "";
    /**
     * <code>string name6 = 3;</code>
     */
    public java.lang.String getName6() {
      java.lang.Object ref = name6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name6 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getName6Bytes() {
      java.lang.Object ref = name6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name6 = 3;</code>
     */
    public Builder setName6(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name6 = 3;</code>
     */
    public Builder clearName6() {
      
      name6_ = getDefaultInstance().getName6();
      onChanged();
      return this;
    }
    /**
     * <code>string name6 = 3;</code>
     */
    public Builder setName6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name6_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HelloRequest4)
  }

  // @@protoc_insertion_point(class_scope:HelloRequest4)
  private static final grpc.ca.ChatSupport.HelloRequest4 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ca.ChatSupport.HelloRequest4();
  }

  public static grpc.ca.ChatSupport.HelloRequest4 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloRequest4>
      PARSER = new com.google.protobuf.AbstractParser<HelloRequest4>() {
    @java.lang.Override
    public HelloRequest4 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HelloRequest4(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HelloRequest4> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HelloRequest4> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ca.ChatSupport.HelloRequest4 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

