// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatSupport.proto

package grpc.ca.ChatSupport;

public interface HelloRequest4OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest4)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name4 = 1;</code>
   */
  java.lang.String getName4();
  /**
   * <code>string name4 = 1;</code>
   */
  com.google.protobuf.ByteString
      getName4Bytes();

  /**
   * <code>string name5 = 2;</code>
   */
  java.lang.String getName5();
  /**
   * <code>string name5 = 2;</code>
   */
  com.google.protobuf.ByteString
      getName5Bytes();

  /**
   * <code>string name6 = 3;</code>
   */
  java.lang.String getName6();
  /**
   * <code>string name6 = 3;</code>
   */
  com.google.protobuf.ByteString
      getName6Bytes();
}
