// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatSupport.proto

package grpc.ca.ChatSupport;

public interface HelloReply4OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply4)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message4 = 1;</code>
   */
  java.lang.String getMessage4();
  /**
   * <code>string message4 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessage4Bytes();
}
