// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatSupport.proto

package grpc.ca.ChatSupport;

public final class NewServiceImpl3 {
  private NewServiceImpl3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest4_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply4_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatSupport.proto\"<\n\rHelloRequest4\022\r\n\005" +
      "name4\030\001 \001(\t\022\r\n\005name5\030\002 \001(\t\022\r\n\005name6\030\003 \001(" +
      "\t\"\037\n\013HelloReply4\022\020\n\010message4\030\001 \001(\t2C\n\013ch" +
      "atSupport\0224\n\016GetChatSupport\022\016.HelloReque" +
      "st4\032\014.HelloReply4\"\000(\0010\001B(\n\023grpc.ca.ChatS" +
      "upportB\017NewServiceImpl3P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest4_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest4_descriptor,
        new java.lang.String[] { "Name4", "Name5", "Name6", });
    internal_static_HelloReply4_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply4_descriptor,
        new java.lang.String[] { "Message4", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
